config/routes.rb
PolyBite::Application.routes.draw do
  get "taggings/create"
  resources :study_list_items

  devise_for :users
  
  resources :users
  resources :links
  resources :tags
  resources :taggings
  
  get "static_pages/index"
  
  match 'about', to: 'static_pages#about', via: :get
  get "static_pages/about"

  root 'static_pages#index'
  

  

end

app/models/link.rb
require 'nokogiri'
require 'open-uri'

class Link < ActiveRecord::Base
  belongs_to :user
  has_many :study_list_items
  has_many :taggings
  has_many :tags, through: :taggings

  def parse_url
    doc = Nokogiri::HTML(open(self.url))
    self.title = doc.title
    dom_url = Domainatrix.parse(self.url)
    root_url = url.split(".#{dom_url.public_suffix}")[0] + ".#{dom_url.public_suffix}"
    doc = Nokogiri::HTML(open(root_url))
    self.author = doc.title
  end

end

app/models/study_list_item.rb
class StudyListItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :links, through: :taggings
  validates_uniqueness_of :name
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :link
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :links
  has_many :study_list_items

  def full_name
    self.first_name + " " + self.last_name
  end

  def gravatar_img
    url = Gravatar.new(self.email).image_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:first_name, :last_name, :date_of_birth, :location, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]

  def show
    @link = Link.find(params[:id])
  end

  def index
    @links = Link.all
  end

  def new
    @link = Link.new
  end

  def update
    @link = Link.find(params[:id])
    @link.update(link_params)
    
    redirect_to links_path 
  end

  def create
    @link = Link.new(link_params)
    @link.user_id = current_user
    @link.parse_url
    @link.save
    redirect_to links_path
  end

  private
  def link_params
    params.require(:link).permit(:url)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/study_list_items_controller.rb
class StudyListItemsController < ApplicationController

  def create
    study_list_item = StudyListItem.create(user_id: params[:user_id], link_id: params[:link_id])
    render text: study_list_item.inspect
  end

end

app/controllers/taggings_controller.rb
class TaggingsController < ApplicationController
  def create
    tag = Tag.find_by_name(params[:tagging][:tag])
    if tag
      Tagging.create(link_id: params[:tagging][:link_id], tag_id: tag.id)
    else
      tag = Tag.create(name: params[:tagging][:tag]) 
      Tagging.create(link_id: params[:tagging][:link_id], tag_id: tag.id)
    end
    redirect_to :back
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/study_list_items_helper.rb
module StudyListItemsHelper
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "PolyBite" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "partials/navbar" %>
    <%= render "partials/notices" %>

    <%= yield %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/links/index.html.erb
<div class="panel">
  <h1>All the links</h1>
</div>

<div class="container">
  <div class="small-12 large-4 columns">
    <%= form_for(Link.new) do |f| %>
      <fieldset>
        <legend>Add a link</legend>
        
        <div class="row">
          <div class="small-4 columns">
            <%= f.label :url, class: "right inline" %>
          </div>
          <div class="small-8 columns">
            <%= f.text_field :url, :autofocus => true %>
          </div>
        </div>
        
        <div class="row">
          <div class="small-8 small-offset-4 columns">
            <%= f.submit class: "button small expand" %>
          </div>
        </div>

      </fieldset>
    <% end %>
  </div>
  <div class="small-12 large-8 columns">

    <% @links.each do |link| %>
      
      <h4><%= link_to link.title.html_safe, link.url, target: "blank", class: "index-link", "data-link-id" => link.id, "data-user-id" => current_user.id %></h4>
      <p>By <%= link.author %></p>
      <ul class="inline-list">
        <% link.tags.each do |tag| %>
          <li class="label"><%= tag.name %></li>
        <% end %>
      </ul>
        
    <% end %>
  </div>
</div>

app/views/links/new.html.erb
<div class="row">
  <div class="large-8 columns large-centered">
    <%= form_for @link do |f| %>
      <fieldset>
        <legend>Add a link</legend>
        
        <div class="row">
          <div class="small-4 columns">
            <%= f.label :url, class: "right inline" %>
          </div>
          <div class="small-8 columns">
            <%= f.text_field :url, :autofocus => true %>
          </div>
        </div>
        
        <div class="row">
          <div class="small-8 small-offset-4 columns">
            <%= f.submit class: "button small expand" %>
          </div>
        </div>

      </fieldset>
    <% end %>
  </div>
</div>

app/views/links/show.html.erb
<div class="container">
  <div class="small-12 large-8 large-centered columns">
    <h4><%= link_to @link.title.html_safe, @link.url, id: "target-link"  %></h4>
    <p>By <%= @link.author %></p>
    <ul class="inline-list">
      <% @link.tags.each do |tag| %>
        <li class="label"><%= tag.name %></li>
      <% end %>
    </ul>
    <%= form_for Tagging.new, remote: true do |f| %>
      <%= f.hidden_field :link_id, value: @link.id %>
      
      <div class="row">
        <div class="small-2 columns">
          <%= f.label :tag, class: "right inline" %>
        </div>
        <div class="small-10 columns">
          <%= f.text_field :tag %>
        </div>
      </div>

      <div class="row">
        <div class="small-10 small-offset-2 columns">
          <%= f.submit "Add a tag", class: "button small expand" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script>
  $(document).ready(function(){
    window.open($("#target-link").attr("href"),'_blank');
  }) 
</script>

app/views/partials/_navbar.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1>
        <a href="/">PolyBite</a>
      </h1>
    </li>
  </ul>
  <div class="top-bar-section">
    <ul class="right">
      <li>
        <%= link_to "Learn", links_path %>
      </li>
      <!-- <li><a href="#">Teach</a></li> -->
      <li><a href="#">About</a></li>
      <% if current_user %>
        <li>
          <%= link_to "My profile", user_path(current_user) %>
        </li>
        <li>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        </li>
        <li>
          <%= link_to "Edit Account", edit_user_registration_path(current_user) %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign In", new_user_session_path %>
        </li>
        <li>
          <%= link_to "Sign Up", new_user_registration_path %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/partials/_notices.html.erb
<% flash.each do |key, value| %>
  <div class="alert-box"><%= value %></div>
<% end %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/index.html.erb
<div class="container">
  <div class="small-12 columns">
    <h1>PolyBite</h1>
    <p>Learn whatever, wherever, whenever!</p>
  </div>
</div>

app/views/taggings/create.html.erb
<h1>Taggings#create</h1>
<p>Find me in app/views/taggings/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="container">
  <div class="small-12 columns">
    <h1>Your profile</h1>
  </div>
</div>
<div class="container">
  <div class="small-12 large-3 columns">
    <div class="panel clearfix">
      <%= image_tag @user.gravatar_img, class: "left" %>
      <p class="right"><%= @user.full_name %></p>
    </div>
  </div>
  <div class="small-12 large-9 columns">
    <% @user.links.each do |link| %>
      <div class="panel">
        <h4><%= link_to link.title.html_safe, link.url %></h4>
        <p>By <%= link.author %></p>
      </div>
    <% end %>
  </div>
</div>